Add support for getting templates from Mandrill.
centralapp/mandrill pull request #1
Opened 2020-11-12 11:57 UTC by asheshambasta

We need to merge this into the nix branch and submit an upstream PR that adds nix support with our additional features.

2020-11-12 13:26 UTC, BrechtSerckx requested changes
Some small changes

2020-11-12 13:26 UTC, BrechtSerckx commented on src/Network/API/Mandrill/Templates.hs
> +getTemplates k labelFilt = toMandrillResponse GetTemplates (GetTemplatesRq k labelFilt)
```suggestion
getTemplates k labelFilt = toMandrillResponse GetTemplates $ GetTemplatesRq k labelFilt
```

2020-11-12 13:26 UTC, BrechtSerckx commented on src/Network/API/Mandrill/Templates/Types.hs
> +    -- ^ An optional Template label (for searching)
```suggestion
```

duplicate line here

2020-11-12 13:28 UTC, asheshambasta commented on src/Network/API/Mandrill/Templates/Types.hs
> +    -- ^ An optional Template label (for searching)
This is a stylish-haskell bug AFAICS.

2020-11-12 13:48 UTC, BrechtSerckx commented on src/Network/API/Mandrill/Templates/Types.hs
> +    -- ^ An optional Template label (for searching)
Hmm, that sucks

2020-11-12 13:49 UTC, BrechtSerckx approved these changes

2020-11-16 11:47 UTC, merged

2020-11-16 11:47 UTC, asheshambasta commented
@BrechtSerckx fyi: merged since you had approved it.